Break android build tools dependency with compileOnly
nbaztec/coveralls-jacoco-gradle-plugin pull request #31
Opened 2021-01-19 07:58 UTC by nhoughto

Reduces the number of deps that users of the plugin need

2021-01-19 16:11 UTC, nbaztec requested changes
Thanks for the PR, a few nit picks and we're good to go.

2021-01-19 21:12 UTC, nhoughto commented on src/test/kotlin/SourceReportParserTest.kt
> +        SourceReportParser.hasAndroidClasses = true
so by default the test will have android classes, because they are on the test classpath. So there should only need 1 extra test, to test the normal source behaviour when android == false.

2021-01-21 09:39 UTC, nbaztec approved these changes

2021-01-21 09:39 UTC, merged

2021-01-22 13:05 UTC, nbaztec commented
the change did not work for non-android projects and was failing at runtime due to missing dependency on android build extension. Had to be unfortunately  reverted in #33

2021-01-22 20:09 UTC, nhoughto commented
Surprising, what was the error?
On 23 Jan 2021, 12:05 AM +1100, Nisheeth Barthwal <notifications@github.com>, wrote:
> the change did not work for non-android projects and was failing at runtime due to missing dependency on android build extension. Had to be unfortunately reverted in #33
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-22 21:38 UTC, nbaztec commented
Running some more tests lead to the discovery of exception `NoClassDefFoundError` being incorrect. It should've been `ClassNotFoundException` and hence the true exception was leaking out to the code.

I've opened a PR to fix this in #34
Would merge it after finding a way to test this better to avoid future regressions.

2021-01-22 22:33 UTC, nhoughto commented
ah such a simple mistake! 🤦